import { test, expect } from '@playwright/test';

test('TC01-test-login-success', async ({ page }) => {
  await page.goto('https://ecommerce-playground.lambdatest.io/index.php?route=account/login');
  await page.getByRole('textbox', { name: 'E-Mail Address' }).click();
  await page.getByRole('textbox', { name: 'E-Mail Address' }).fill('test_user@lambdatest.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Test@12345');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('heading', { name: 'My Account' }).click();
  await expect(page.locator('#content')).toContainText('My Account');
});
test('TC02-test-edit-success', async ({ page }) => {
  await page.goto('https://ecommerce-playground.lambdatest.io/index.php?route=account/login');
  await page.getByRole('textbox', { name: 'E-Mail Address' }).click();
  await page.getByRole('textbox', { name: 'E-Mail Address' }).fill('test_user@lambdatest.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Test@12345');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: ' Edit Account' }).click();
  await page.getByRole('textbox', { name: 'First Name *' }).click();
  await page.getByRole('textbox', { name: 'First Name *' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'First Name *' }).fill('Ngan');
  await page.getByRole('textbox', { name: 'Last Name*' }).click();
  await page.getByRole('textbox', { name: 'Last Name*' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Last Name*' }).fill('Bao');
  await page.getByRole('textbox', { name: 'Telephone*' }).click();
  await page.getByRole('textbox', { name: 'Telephone*' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Telephone*' }).fill('0987654321');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('heading', { name: 'My Account' }).click();
  await expect(page.locator('#content')).toContainText('My Account');
  await page.getByText('Success: Your account has').click();
  await expect(page.locator('#account-account')).toContainText('Success: Your account has been successfully updated.');
  await page.getByRole('link', { name: ' Edit Account' }).click();
  await expect(page.getByRole('textbox', { name: 'First Name *' })).toHaveValue('Ngan');
  await expect(page.getByRole('textbox', { name: 'Last Name*' })).toHaveValue('Bao');
  await expect(page.getByRole('textbox', { name: 'Telephone*' })).toHaveValue('0987654321');
});

test('TC03-test-change-password-success', async ({ page }) => {
  await page.goto('https://ecommerce-playground.lambdatest.io/index.php?route=account/login');
  await page.getByRole('textbox', { name: 'E-Mail Address' }).click();
  await page.getByRole('textbox', { name: 'E-Mail Address' }).fill('test_user@lambdatest.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Test@12345');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: ' Change your password' }).click();
  await page.getByRole('textbox', { name: 'Password*' }).click();
  await page.getByRole('textbox', { name: 'Password*' }).fill('Ngan@123456');
  await page.getByRole('textbox', { name: 'Password Confirm*' }).click();
  await page.getByRole('textbox', { name: 'Password Confirm*' }).fill('Ngan@123456');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('heading', { name: 'My Account' }).click();
  await expect(page.locator('#content')).toContainText('My Account');
  await expect(page.locator('#account-account')).toContainText('Success: Your password has been successfully updated.');
  await page.getByRole('link', { name: ' Logout' }).click();
  await expect(page.locator('h1')).toContainText('Account Logout');
  await page.getByRole('link', { name: ' Login' }).click();
  await page.getByRole('textbox', { name: 'E-Mail Address' }).click();
  await page.getByRole('textbox', { name: 'E-Mail Address' }).fill('test_user@lambdatest.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Ngan@123456');
  await page.getByRole('button', { name: 'Login' }).click();
  await expect(page.locator('#content')).toContainText('My Account');
});
test('TC04-test-change-address-success', async ({ page }) => {
  await page.goto('https://ecommerce-playground.lambdatest.io/index.php?route=account/address/add');
  await page.getByRole('textbox', { name: 'E-Mail Address' }).click();
  await page.getByRole('textbox', { name: 'E-Mail Address' }).fill('test_user@lambdatest.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Ngan@123456');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: 'New Address' }).click();
  await page.getByRole('textbox', { name: 'First Name*' }).click();
  await page.getByRole('textbox', { name: 'First Name*' }).fill('Ngan');
  await page.getByRole('textbox', { name: 'Last Name*' }).click();
  await page.getByRole('textbox', { name: 'Last Name*' }).fill('Bao');
  await page.getByRole('textbox', { name: 'Company' }).click();
  await page.getByRole('textbox', { name: 'Company' }).fill('Company');
  await page.getByRole('textbox', { name: 'Company' }).click();
  await page.getByRole('textbox', { name: 'Address 1*' }).click();
  await page.getByRole('textbox', { name: 'Address 1*' }).fill('62 Nguyen Thuong Hien');
  await page.getByRole('textbox', { name: 'Address 2' }).click();
  await page.getByRole('textbox', { name: 'Address 2' }).fill('Address 2');
  await page.getByRole('textbox', { name: 'City*' }).click();
  await page.getByRole('textbox', { name: 'City*' }).fill('Danang');
  await page.getByRole('textbox', { name: 'Post Code*' }).click();
  await page.getByRole('textbox', { name: 'Post Code*' }).fill('50000');
  await page.getByLabel('Country').selectOption('230');
  await page.getByLabel('Region / State').selectOption('3767');
  await page.getByRole('button', { name: 'Continue' }).click();
  await expect(page.locator('#content')).toContainText('Ngan BaoCompany62 Nguyen Thuong HienAddress 2Danang 50000Da NangViet Nam');
  await page.getByText('Your address has been').click();
  await expect(page.locator('#account-address')).toContainText('Your address has been successfully added');
  await expect(page.locator('h1')).toContainText('Address Book Entries');
});
test('TC05-test-logout-success', async ({ page }) => {
  await page.goto('https://ecommerce-playground.lambdatest.io/index.php?route=account/login');
  await page.getByRole('textbox', { name: 'E-Mail Address' }).click();
  await page.getByRole('textbox', { name: 'E-Mail Address' }).fill('https://ecommerce-playground.lambdatest.io/index.php?route=account/account');
  await page.getByRole('textbox', { name: 'E-Mail Address' }).click();
  await page.getByRole('textbox', { name: 'E-Mail Address' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'E-Mail Address' }).fill('test_user@lambdatest.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Ngan@123456');
  await page.getByRole('button', { name: 'Login' }).click();
  await expect(page.locator('#content')).toContainText('My Account');
  await page.getByRole('link', { name: ' Logout' }).click();
  await expect(page.locator('h1')).toContainText('Account Logout');
  await expect(page.locator('h1')).toContainText('Account Logout');
});